name: Deploy to AWS

on:
  push:
    branches:
      - main  # main 브랜치에 push 시 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y ssh python3 python3-venv python3-pip git

    - name: Set up Python
      run: |
        python3 -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements/base.txt  # requirements.txt에 정의된 의존성 설치

    - name: Run migrations and collectstatic
      run: |
        source venv/bin/activate
        python manage.py migrate  # 데이터베이스 마이그레이션
        python manage.py collectstatic --noinput  # static 파일 수집

    - name: Deploy to AWS
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.AWS_HOST }}
        username: ${{ secrets.AWS_USER }}
        key: ${{ secrets.AWS_SSH_KEY }}
        script: |
          cd /home/Literature_DRF  # Django 프로젝트 디렉토리로 이동
          source venv/bin/activate  # 가상 환경 활성화
          git pull origin main  # 최신 코드를 pull
          pip install -r requirements/base.txt  # 의존성 설치
          python manage.py migrate  # 데이터베이스 마이그레이션
          python manage.py collectstatic --noinput  # static 파일 수집
          sudo systemctl restart gunicorn  # 프로세스 재시작 (Gunicorn 사용 예시)
