name: Deploy to AWS

on:
  push:
    branches:
      - main  # Run the action on every push to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y ssh python3 python3-venv python3-pip git

    - name: Setup Python environment
      run: |
        python3 -m venv venv
        source venv/bin/activate
        pip install --upgrade pip

    - name: Install project dependencies
      run: |
        source venv/bin/activate
        pip install -r requirements/base.txt  # Install dependencies from your requirements.txt

    - name: Run migrations
      run: |
        source venv/bin/activate
        python manage.py migrate  # Apply Django migrations

    - name: Collect static files
      run: |
        source venv/bin/activate
        python manage.py collectstatic --noinput  # Collect static files for deployment

    - name: Deploy to AWS via SSH
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.AWS_HOST }}  # EC2 instance host
        username: ${{ secrets.AWS_USER }}  # SSH user
        key: ${{ secrets.AWS_SSH_KEY }}  # SSH private key for EC2
        port: 22
        script: |
          cd /home/Literature_DRF  # Navigate to your project directory
          source venv/bin/activate  # Activate the virtual environment
          git pull origin main  # Pull the latest changes from the 'main' branch
          pip install -r requirements/base.txt  # Install any new dependencies
          python manage.py migrate  # Run migrations if needed
          python manage.py collectstatic --noinput  # Collect static files
          sudo systemctl restart your-web-server.service  # Restart the web server (e.g., Gunicorn, Nginx)

