# GitHub Actions 워크플로우 파일 예시
name: Deploy to AWS

on:
  push:
    branches:
      - main  # main 브랜치에 push 시 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y ssh

    - name: Deploy to AWS
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.AWS_HOST }}
        username: ${{ secrets.AWS_USER }}
        key: ${{ secrets.AWS_SSH_KEY }}
        port: 22
        script: |
          # Git 상태 확인 및 최신 코드 가져오기
          git fetch origin
          git reset --hard origin/main
          # 나머지 배포 작업 (가상환경, 마이그레이션 등)
